name: Daily VCP Stock Scan

on:
  schedule:
    - cron: '30 7 * * 1-5' # 台灣時間週一至週五 15:30 執行
  workflow_dispatch:

jobs:
  run-vcp-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run VCP Scan script
        run: |
          python main.py
